### ISSUE TITLE
[Help] Unable to use leaf to initialize navbar

### ISSUE THREAD

**Issue by Compro-Prasad** [conao3/leaf.el#267]
The original issue was reported at https://github.com/conao3/navbar.el/issues/3 . But it seems to be a problem with `leaf`.

**Comment by Compro-Prasad** [comment]
I expanded the macro using your suggestion:
```
(defmacro p (form)
  "Output pretty `macroexpand-1'ed form of given FORM."
  `(progn
     (pp (macroexpand-1 ',form))
     nil))
(p
 (leaf navbar
   :load-path "~/Downloads/github.com/conao3/navbar.el"
   :config
   (setq navbar-item-list '("Hello, World!"))
   (navbar-mode 1)))
```
This gives the following output in the `*Messages*` buffer:
```
(prog1 'navbar
  (leaf-handler-leaf-protect navbar
    (add-to-list 'load-path "~/Downloads/github.com/conao3/navbar.el")
    (leaf-handler-package navbar navbar nil)
    (setq navbar-item-list
          '("Hello, World!"))
    (navbar-mode 1)))
nil
```

**Comment by Compro-Prasad** [comment]
I think I get it now. I have set `leaf-ensure` to `t` which always checks if the package is in the package list. But `navbar` is not available in any repositories. I tried the same with `use-package` and it works there. So, its better to prioritize `:load-path` over `leaf-ensure`.

**Comment by conao3** [comment]
Good. I understood.
Setting `leaf-defaults` to `:ensure t` is convenient on the surface, but you discard another convenience. I didn't use that feature, so I didn't have to worry about such a problem.

`use-package` manage package settings, but `leaf` manages package configuration fragments and their aggregations. If you use `leaf` under such a philosophy, you may set `leaf-defaults` to `nil` and type few characters.

The following settings are in [my dotfiles](https://github.com/conao3/dotfiles/blob/master/.dotfiles/.emacs.d/init.el).
```elisp
(leaf *minor-mode
  :config
  (leaf posframe
    :ensure t
    :when (version<= "26.1" emacs-version)
    :when window-system
    :config
    (leaf ivy-posframe
      :doc "Using posframe to show Ivy"
      :after ivy
      :ensure t
      :custom ((ivy-posframe-mode . t)
               (ivy-posframe-height-alist . '((swiper . 30) (t . 40)))
               (ivy-posframe-display-functions-alist
                . '((swiper . nil) (t . ivy-posframe-display-at-frame-center)))
               (ivy-posframe-parameters . '((left-fringe . 10)))))

    (leaf company-posframe
      :doc "Use a posframe as company candidate menu"
      :ensure t
      :after company
      :custom ((company-posframe-mode . t)))

    (leaf flycheck-posframe
      :ensure t
      :after flycheck
      :custom ((flycheck-posframe-mode . t)))

    (leaf which-key-posframe
      :ensure t
      :after which-key
      :custom ((which-key-posframe-mode . t)))

    (leaf ddskk-posframe
      :doc "Show Henkan tooltip for ddskk via posframe"
      :after skk
      :el-get conao3/ddskk-posframe.el
      :custom ((ddskk-posframe-mode . t))))

  ;; other minor-mode packages...
)
```
By hierarchically managing package settings, I can avoid loading and installing child packages when the parent package does not work.

Thanks for your report.
