### ISSUE TITLE
:config not working when :bind is used?

### ISSUE THREAD

**Issue by Red-Portal** [conao3/leaf.el#270]
```elisp
(leaf evil
  :require windmove
  :ensure t
  :bind
  ((:evil-normal-state-map
    ("J" . next-line-fast)
    ("K" . prvious-line-fast))
   (:evil-normal-state-map
    ("C-h" . windmove-left)
    ("C-j" . windmove-down)
    ("C-k" . windmove-up)
    ("C-l" . windmove-right)))
  :config
  (evil-mode 1)
  (turn-on-evil-mode)
  )
```

when the `:bind` keyword is used, `(evil-mode 1) (turn-on-evil-mode)` statement is not evaluated. (evil mode is not enabled on startup). However when I remove the `:bind` part it works as expected. To ensure both, I need to place somewhere else `(evil-mode 1) (turn-on-evil-mode)`.

By the way, this is a personal question: how is the development of `feather` going?

**Comment by conao3** [comment]
First, if you encounter a case which `leaf` is not working, you expand `leaf`.

`macroexpand-1` provide you below form.

```elisp
(prog1 'evil
  (leaf-handler-leaf-protect evil
    (autoload (function next-line-fast) "evil" nil t)
    (autoload (function prvious-line-fast) "evil" nil t)
    (autoload (function windmove-left) "evil" nil t)
    (autoload (function windmove-down) "evil" nil t)
    (autoload (function windmove-up) "evil" nil t)
    (autoload (function windmove-right) "evil" nil t)
    (leaf-handler-package evil evil nil)
    (leaf-keys
     ((:evil-normal-state-map :package evil
                              ("J" . next-line-fast)
                              ("K" . prvious-line-fast))
      (:evil-normal-state-map :package evil
                              ("C-h" . windmove-left)
                              ("C-j" . windmove-down)
                              ("C-k" . windmove-up)
                              ("C-l" . windmove-right))))
    (eval-after-load 'evil
      '(progn
         (require 'windmove)
         (evil-mode 1)
         (turn-on-evil-mode)))))
```

If you look at the results, you can see why it doesn't work.
To remove this `eval-after-load` set `:leaf-defer` to `nil`.
And it's written here. 
https://github.com/conao3/leaf.el#leaf-defer-keyword

**Comment by conao3** [comment]
Is still an issue? `leaf` doesn't work well for you?

**Comment by Red-Portal** [comment]
Sorry, I completely forgot about this issue. Your suggestion worked. Thanks a lot for the great package!

**Comment by conao3** [comment]
Great. Thanks for using this package!
