### ISSUE TITLE
Setting or customizing variables from plstore

### ISSUE THREAD

**Issue by d125q** [conao3/leaf.el#276]
I use [`plstore.el`](https://github.com/emacs-mirror/emacs/blob/master/lisp/plstore.el) to store some secret information.  It would be nice of `leaf.el` included support to set or customize variables with values from a plstore.

For example, if `my-plstore` contains an entry

```elisp
("erc" :sercret-erc-server "server" :secret-erc-nickserv-passwords ((network (("nick" . "password")))))
```

then a leaf block

```elisp
(leaf erc
  :plstore-setq
  ((erc-server erc-nickserv-passwords) . my-plstore))
```

would expand to

```elisp
(setq erc-server "server"
      erc-nickserv-passwords '((network (("nick" . "password")))))
```

If you think this is a good idea, I can work on a PR to implement it.  I also propose we add `:plstore-custom` and `:plstore-setq-default` that operate in the same manner.

**Comment by conao3** [comment]
Good!
However, I now know that `setq` should not be used for customization.
When you add `:plstore-setq`, you may also want to provide `:plstore-custom`.

And there is a room to the conversation to that leaf grammar. There should be a more flexible and friendly way to describe the keyword and argument.

**Comment by conao3** [comment]
I thought I would use `auth-source` for that purpose. When adding this keyword, it should be considered at the same time to add a related keyword.

**Comment by conao3** [comment]
This feature is merged 🎉
