### ISSUE TITLE
:hook cannot handle lambda with multiple expressions

### ISSUE THREAD

**Issue by taku0** [conao3/leaf.el#295]
## Description

If a lambda expression with multiple expressions are passed to `:hook`, it is not recognized as a function.

## Issue leaf-block
```elisp
(leaf hook
 :leaf-autoload nil
 :hook (foo-hook . (lambda () (foo) (bar))))
```

## Expected output from macroexpand-1 of the leaf-block
```elisp
(prog1 (quote hook)
  (leaf-handler-leaf-protect
      hook
    (add-hook (quote foo-hook) (function (lambda nil (foo) (bar))))))
```

## Actual output
```elisp
(prog1 (quote hook)
  (leaf-handler-leaf-protect
      hook
    (add-hook (quote foo-hook) (function hook))
    (add-hook (quote lambda) (function hook))
    (add-hook (quote nil) (function hook))
    (add-hook (quote foo) (function hook))
    (add-hook (quote bar) (function hook))))
```

## Note 

If the lambda has only one expression, it works as expected:

```elisp
(leaf hook
  :leaf-autoload nil
  :hook (foo-hook . (lambda () (foo))))
```
→
```elisp
(prog1 (quote hook)
  (leaf-handler-leaf-protect
      hook
    (add-hook (quote foo-hook) (function (lambda nil (foo))))))
```

Related code: https://github.com/conao3/leaf.el/blob/ae49bbde44e3c553f6a0ff9103175ac581773bf8/leaf.el#L688

## Workaround

Wrapping the body with `progn` works:
```elisp
(leaf hook
 :leaf-autoload nil
 :hook (foo-hook . (lambda () (progn (foo) (bar)))))
```
→
```elisp
(prog1 (quote hook)
  (leaf-handler-leaf-protect
      hook
    (add-hook
     (quote foo-hook)
     (function (lambda nil (progn (foo) (bar)))))))
```

**Comment by conao3** [comment]
I understand this issue.
But because this issue related to LISP limitation, I don't have a solution for now...
Ref: https://github.com/conao3/leaf.el/issues/279

**Comment by taku0** [comment]
How about this procedure: in the computation of `prov` in `leaf-normalize-list-in-list`, if `(memq 'lambda lst)` is non-nil and its 2nd element (i.e. `cadr`) is a list, set `prov` to `(memq 'lambda lst)` and `butlast-n` to `(length prov)`.

For example, `(leaf-normalize-list-in-list '(a b c lambda () (foo) (bar)) 'dotlistp)` results in `((a . (lambda () (foo) (bar))) (b . (lambda () (foo) (bar))) (c . (lambda () (foo) (bar))))`.
While this makes the symbol `lambda` cannot be used as a variable, `labmda` is unlikely used as a variable name, and we are already treating `lambda` (with one expression) specially.

**Comment by conao3** [comment]
It is a concern about treat setting list with *distribution* feature.
But this is a big problem that causes a bug. I would like to add it as an unstable feature.

**Comment by conao3** [comment]
done, check HEAD please!

**Comment by taku0** [comment]
It works as expected. Thank you!
