### ISSUE TITLE
:hook should not autoload lambda expressions

### ISSUE THREAD

**Issue by taku0** [conao3/leaf.el#296]
## Description

If a lambda expression is passed to `:hook`, it generates autoload for the lambda expression. It results in `wrong-type-argument symbolp`.

## Issue leaf-block
```elisp
(leaf hook
  :hook (foo-hook . (lambda () (foo))))
```

## Expected output from macroexpand-1 of the leaf-block
```elisp
(prog1 (quote hook)
  (leaf-handler-leaf-protect
      hook
    (add-hook (quote foo-hook) (function (lambda nil (foo))))))
```

## Actual output

```elisp
(prog1 (quote hook)
  (leaf-handler-leaf-protect
      hook
    (autoload (function (lambda nil (foo))) "hook" nil t)
    (add-hook (quote foo-hook) (function (lambda nil (foo))))))
```

**Comment by conao3** [comment]
This issue seems to solved at recent commit. Check HEAD, please!

**Comment by taku0** [comment]
LGTM! Thank you!
