### ISSUE TITLE
Don't provide a leaf-tests feature

### ISSUE THREAD

**Issue by tarsius** [conao3/leaf.el#301]
`leaf-tests.el` should not `provide` a feature because it isn't a *library* intended for users to `require`. Only libraries should provide features, test files and other maintenance scripts should be loaded using `load` instead. You already do that by (conceptually) using `emacs -l load-leaf.el` in the Makefile, so it should be safe to just drop the `provide` form.

**Comment by conao3** [comment]
OK. I'll fix it.

**Comment by conao3** [comment]
I've submitted org-re-reveal too. https://gitlab.com/oer/org-re-reveal/merge_requests/25

**Comment by conao3** [comment]
How about my fix? Do you have more any suggestions?

**Comment by tarsius** [comment]
That works for me thanks! No.
