### ISSUE TITLE
Packages' bindings are not being loaded on emacs startup after using :bind

### ISSUE THREAD

**Issue by nikyq** [conao3/leaf.el#355]
## Description

Using :bind keyword inside some package's leaf block seems to disable package's default bindings. For instance, C-x g doesn't open magit-status. After I manually invoke it using M-x, bindings come back to normal as expected. I suppose it's an issue related to package loading precedence.

## Issue leaf-block
```elisp
(leaf evil
  :straight t
  :config (evil-mode 1)
  :bind ((:evil-insert-state-map ("C-k" . nil)) ; conflict with other ^k bindings
            (:minibuffer-local-map  ("C-j" . next-line-or-history-element)
                                                 ("C-k" . previous-line-or-history-element))))
```
## Output from macroexpand-1 of the leaf-block
```elisp
(prog1 'evil
  (leaf-handler-leaf-protect evil
    (unless
	(fboundp 'next-line-or-history-element)
      (autoload #'next-line-or-history-element "evil" nil t))
    (unless
	(fboundp 'previous-line-or-history-element)
      (autoload #'previous-line-or-history-element "evil" nil t))
    (declare-function next-line-or-history-element "evil")
    (declare-function previous-line-or-history-element "evil")
    (defvar evil-insert-state-map)
    (defvar minibuffer-local-map)
    (straight-use-package 'evil)
    (leaf-keys
     ((:evil-insert-state-map :package evil
			      ("C-k"))
      (:minibuffer-local-map :package evil
			     ("C-j" . next-line-or-history-element)
			     ("C-k" . previous-line-or-history-element))))
    (eval-after-load 'evil
      '(progn
	 (evil-mode 1)))))
```
After restarting emacs, the above code results in evil-mode being not toggled by default alongside all other evil commands not showing. After I invoke evil-mode, the commands show up, but evil-mode's still not turned on. I have to M-x evil-mode one more time in order to turn on evil mode. I checked out that everything works fine without the :bind section.

## Issue leaf-block
```elisp
(leaf evil
  :straight t
  :config (evil-mode 1)
  :bind ("C-c C-c" . eval-last-sexp))
```
## Output from macroexpand-1 of the leaf-block
```elisp
(prog1 'evil
  (leaf-handler-leaf-protect evil
    (unless
	(fboundp 'eval-last-sexp)
      (autoload #'eval-last-sexp "evil" nil t))
    (declare-function eval-last-sexp "evil")
    (straight-use-package 'evil)
    (leaf-keys
     (("C-c C-c" . eval-last-sexp)))
    (eval-after-load 'evil
      '(progn
	 (evil-mode 1)))))
```
As a test, I tried the above code and found out that eval-last-sexp got bound to C-c C-c while evil-mode was still not being toggled after emacs restart.

## Issue leaf-block
```elisp
(leaf magit
  :straight t
  :bind (:magit-file-mode-map ("C-c C-c" . magit-stage-current-buffer-and-commit)))
```
## Output from macroexpand-1 of the leaf-block
```elisp
(prog1 'magit
  (leaf-handler-leaf-protect magit
    (unless
	(fboundp 'magit-stage-current-buffer-and-commit)
      (autoload #'magit-stage-current-buffer-and-commit "magit" nil t))
    (declare-function magit-stage-current-buffer-and-commit "magit")
    (defvar magit-file-mode-map)
    (straight-use-package 'magit)
    (leaf-keys
     ((:magit-file-mode-map :package magit
			    ("C-c C-c" . magit-stage-current-buffer-and-commit))))))
```
Same thing goes for magit. After emacs restart, as I explained above, C-x g was not calling magit-status and C-c C-c wasn't also working. (magit-stage-current-buffer-and-commit is a custom command I created. I don't think its implementation is related to the issue)

## Issue leaf-block
```elisp
(leaf magit
  :straight t
  :bind ("C-c C-c" . magit-stage-current-buffer-and-commit))
```
## Output from macroexpand-1 of the leaf-block
```elisp
(prog1 'magit
  (leaf-handler-leaf-protect magit
    (unless
	(fboundp 'magit-stage-current-buffer-and-commit)
      (autoload #'magit-stage-current-buffer-and-commit "magit" nil t))
    (declare-function magit-stage-current-buffer-and-commit "magit")
    (straight-use-package 'magit)
    (leaf-keys
     (("C-c C-c" . magit-stage-current-buffer-and-commit)))))
```
I tried binding C-c C-c to global. As a result, C-x g wasn't still working, but C-c C-c worked.

**Comment by conao3** [comment]
Thanks for writing such a detail issue and your debugging process.
But please describe the issue you face more simple and short.

I welcome close this issue and please create another simple issue to describe.

**Comment by conao3** [comment]
Move this issue to #356
