### ISSUE TITLE
:bind keyword breaks package setup at emacs startup

### ISSUE THREAD

**Issue by nikyq** [conao3/leaf.el#356]
## Description

Using :bind keyword inside some package's leaf block seems to disable the package's default bindings and other configurations. The configurations I set up inside the leaf block (:config (evil-mode 1) for example) are ignored. The bindings specified by :bind keyword work when I bind them globally, but not when I do to a specific map. If I remove the section with :bind keyword, everything works as expected. I've currently experienced the issue with evil and magit and not tested others much.

**Comment by conao3** [comment]
Thanks for rewriting issue.
There is no `leaf` block so I can't suggest a concrete example.
But maybe you want is `:leaf-defer nil`. Ref: https://github.com/conao3/leaf.el#leaf-defer-keyword

**Comment by conao3** [comment]
This issue solved? Did the message I sent help?

**Comment by conao3** [comment]
Close. Feel free to reopen this issue if your problem has still remained.
