### ISSUE TITLE
request: notify forgotten dot in :custom

### ISSUE THREAD

**Issue by yonta** [conao3/leaf.el#362]
## Description

In `:custom` macro, forgotten dot arguments (not dot pair but list) give no errors.
On the other hand, same mistake gives error in `:bind` macro.

## Issue leaf-block
```elisp
(leaf hoge
  :custom
  (variable t))  ;; Oops, I forget dot
```

## Expected output from macroexpand-1 of the leaf-block

It is mistake.
I want to write this.

```elisp
(leaf hoge
  :custom
  (variable . t))
```

But, leaf.el expand it with no errors.

```elisp
(prog1 'hoge
  (leaf-handler-leaf-protect hoge
    (custom-set-variables
     '(variable nil "Customized with leaf in hoge block")
     '(t nil "Customized with leaf in hoge block"))))
```

**Comment by conao3** [comment]
I hope that. But this issue is hard basically.
The current leaf DSL is too huge. For this example, leaf cannot understands below three DSL has a notational difference.
```emacs-lisp
(leaf hoge
  :custom (variable t))

(leaf hoge
  :custom (variable t . nil))

(leaf hoge
  :custom ((variable t) . nil))
```

All example is expanded like as below.
```emacs-lisp
(prog1 'hoge
  (leaf-handler-leaf-protect hoge
    (custom-set-variables
     '(variable nil "Customized with leaf in hoge block")
     '(t nil "Customized with leaf in hoge block"))))
```

**Comment by yonta** [comment]
OK, I understand that it looks easy but hard.

In addition after looking your example,
there is another pattern which is not useful in `:custom` macro.
I understand that it occur from same reason of leaf DSL.

```elisp
(leaf hoge
  :custom (x . (1+ 1)))
```

I want that it expands like this,

```elisp
(prog1 'hoge
  (leaf-handler-leaf-protect hoge
    (custom-set-variables
     '(x (1+ 1) "Customized with leaf in hoge block"))))
```

but, no.

```elisp
(prog1 'hoge
  (leaf-handler-leaf-protect hoge
    (custom-set-variables
     '(x nil "Customized with leaf in hoge block")
     '(1+ nil "Customized with leaf in hoge block") ;; oops
     '(1 nil "Customized with leaf in hoge block")))) ;; oops
```

**Comment by conao3** [comment]
It looks like your intention is...
```emacs-lisp
(leaf hoge
  :custom `(x . ,(1+ 1)))
;;=> (prog1 'hoge
;;     (leaf-handler-leaf-protect hoge
;;       (custom-set-variables
;;        '(x 2 "Customized with leaf in hoge block"))))
```

I think my plan to do add `:eval` symbol is help this issue may be.
`:eval` symbol idea comes from [flycheck](https://www.flycheck.org/en/latest/developer/developing.html#a-more-complex-example).

**Comment by conao3** [comment]
`:eval` is works as below in my plan.
This satisfies the need to evaluate at runtime.
I know that some settings may be evaluated during runtime, not during byte compilation.
```emacs-lisp
(leaf hoge
  :custom (x . (:eval (1+ 1))))
;;=> (prog1 'hoge
;;     (leaf-handler-leaf-protect hoge
;;       (custom-set-variables
;;        `(x ,(1+ 1) "Customized with leaf in hoge block"))))
```

**Comment by yonta** [comment]
For second problem, `:eval` keyword looks better.
I am looking forward it.

For first problem, now, I write `:custom` keywords carefully not to forget dot.

**Comment by conao3** [comment]
I think [leaf-convert.el](https://github.com/conao3/leaf-convert.el) would help you (but developing state for now).
It gives usual `progn` convert to `leaf` and `use-package` convert to `leaf` is also will support.

**Comment by conao3** [comment]
I try to solve this issue.
There is one option; raise error or display warnings when detect to attempt to change the constant symbol.
I choice just display warnings. I would not block init.el evaluation still one leaf block is broken.
Please check this feature after MELPA rebuild.

**Comment by yonta** [comment]
Great Job:+1:
Thanks so much.

**Comment by conao3** [comment]
OK, thanks for your report!
