### ISSUE TITLE
Easier way to customize `leaf-normalize`.

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [conao3/leaf.el#374]
## Description

I don't like using cons cells for `:setq` and `:psetq` and would like to change this using `leaf-keywords`.

```(leaf package :setq (a 1) (b 2) (c 3))```

I realize this is not the intended usage, but I find it more concise than adding the ".".

The problem is `leaf-normalize` keeps getting in my way (it messes with `leaf--value`) and there's not easy/convenient way to modify it's clause. `leaf-keywords` is fine because you can just delete/insert values to the plist (digression: personally, I would have preferred an alist because it's easier to do these things with an alist via `setf` and emacs does not have good plist support. Most of the time I when I modify it I end up converting it to an alist making changes, then converting back to a plist.). But you can't do the same thing easily with `leaf-normalize`. 

I think leaf-normalize should be a data structure instead a list of cond case forms. Maybe an alist that accepts whose CDRs should be the normalization form (or potentially a function which normalizes) and CARs are either a list of keys or a function which should take one argument, the key in question, and return t if it should be normalized with its CDR. It's easy enough to convert this data structure to a `cond` via a macro.

**Comment by conao3** [comment]
I think the way to get a list to set value will confuse the user from guessing keywords with `:mode` or `:hook` and miss the opportunity to express a useful format, but I also know that it is needed to set `:custom` in the same format as use-package for many user.

Unfortunately `:custom` is already reserved and many people already use it we will implement it as a `:custom*` keyword.
This has been in the works for a long time, but it didn't support the distribution and flexible formats that custom already had.
Now #375 supports only simple cases `:custom*` has been implemented. I think it's similar to what you want. (`setq` requires only a few changes to the handler.)

Thank you for using leaf!

**Comment by Luis-Henriquez-Perez** [comment]
I was not referring to :custom keyword or Emacs's customize functionality. Im referring to the variable `leaf-normalize` which is used to pre-process `leaf--value`.
Its value is a list of clauses clauses. I'm saying that this variable is not easy to modify. I want to remove :set and :pre-setq from the third clause. I managed to do it but it shouldn't be so hard.

I recommend `leaf-normalize` be a an alist like so: 

```
((list of keywords . normalize form/function) ...)
```
> Thank you for using leaf!

I love using leaf. It is much easier to customize and less obtrusive than use-package. I need to send you a link of my customizations so you can update the link.

**Comment by conao3** [comment]
I'm sorry. I thought it would be easier to understand by giving an example, but I think it makes you confuse.
You do not actually need to edit `leaf-normalize`. Since the list is expanded as `cond`'s body, you can use your original normalizer by just `push`ing it to the top of the list.

However, I do not recommend overriding the keywords I define (I could call it a system keyword.). This customization by many people makes it difficult to develop [leaf-convert](https://github.com/conao3/leaf-convert.el) and other packages that work with `leaf`.
But you can do this. Here's an example I tried with [ppp](https://github.com/conao3/ppp.el).
```emacs-lisp
(ppp-macroexpand
 (leaf cus-start
   :setq ((user-full-name    . "Naoya Yamashita")
          (user-mail-address . "conao3@gmail.com")
          (user-login-name   . "conao3"))))
;;=> (prog1 'cus-start
;;     (leaf-handler-leaf-protect cus-start
;;       (setq user-full-name "Naoya Yamashita")
;;       (setq user-mail-address "conao3@gmail.com")
;;       (setq user-login-name "conao3")))

(push '((memq leaf--key '(:setq))
        (mapcar (lambda (elm)
                  (cons (car elm) (cadr elm)))
                (mapcan 'identity leaf--value)))
      leaf-normalize)
;;=> ...

(ppp-macroexpand
 (leaf cus-start
   :setq ((user-full-name    . "Naoya Yamashita")
          (user-mail-address . "conao3@gmail.com")
          (user-login-name   . "conao3"))))

;;=> Debugger entered--Lisp error: (wrong-type-argument listp "Naoya Yamashita")
;;     cadr((user-full-name . "Naoya Yamashita"))
;;     (cons (car elm) (cadr elm))
;;     ...
;;     call-interactively(eval-print-last-sexp nil nil)
;;     command-execute(eval-print-last-sexp)

(ppp-macroexpand
 (leaf cus-start
   :setq ((user-full-name    "Naoya Yamashita")
          (user-mail-address "conao3@gmail.com")
          (user-login-name   "conao3"))))
;;=> (prog1 'cus-start
;;     (leaf-handler-leaf-protect cus-start
;;       (setq user-full-name "Naoya Yamashita")
;;       (setq user-mail-address "conao3@gmail.com")
;;       (setq user-login-name "conao3")))
```

**Comment by Luis-Henriquez-Perez** [comment]
Oh ok I see. Ah I should have thought of that! 

> This customization by many people makes it difficult to develop leaf-convert and other packages that work with leaf.

I didn't know about leaf-convert. I see an example usage in the its readme but I dont understand what it's for. Could you explain?

**Comment by conao3** [comment]
`leaf-convert` is a package under development that generates `leaf` blocks from plain `elisp` or `use-pacakge` blocks.

In the future, the goal is to automatically convert `use-package`-based init.el to `leaf`-based init.el.

The concern here is the system keyword, if you change the definition of `:setq`, the `leaf` blocks generated by `leaf-convert` will not execute properly.
For safety, it is recommended to push your original keyword with your username as a prefix like `luis-setq`.
```emacs-lisp
(push '((memq leaf--key '(:luis-setq))
        (mapcar (lambda (elm)
                  (cons (car elm) (cadr elm)))
                (mapcan 'identity leaf--value)))
      leaf-normalize)
;;=> ...

(setq leaf-keywords
      (leaf-insert-list-before leaf-keywords :setq
        '(:luis-setq `(,@(mapcar (lambda (elm) `(setq ,(car elm) ,(cdr elm))) leaf--value) ,@leaf--body))))
;;=> ...

(ppp-macroexpand
 (leaf cus-start
   :luis-setq ((user-full-name    . "Naoya Yamashita")
               (user-mail-address . "conao3@gmail.com")
               (user-login-name   . "conao3"))))
;;=> Debugger entered--Lisp error: (wrong-type-argument listp "Naoya Yamashita")
;;     cadr((user-full-name . "Naoya Yamashita"))
;;     (cons (car elm) (cadr elm))
;;     ...
;;     call-interactively(eval-print-last-sexp nil nil)
;;     command-execute(eval-print-last-sexp)

(ppp-macroexpand
 (leaf cus-start
   :luis-setq ((user-full-name    "Naoya Yamashita")
               (user-mail-address "conao3@gmail.com")
               (user-login-name   "conao3"))))
;;=> (prog1 'cus-start
;;     (leaf-handler-leaf-protect cus-start
;;       (setq user-full-name "Naoya Yamashita")
;;       (setq user-mail-address "conao3@gmail.com")
;;       (setq user-login-name "conao3")))
```

**Comment by Luis-Henriquez-Perez** [comment]
Thank you for your explanation. I understand now.
