### ISSUE TITLE
Handle :ensure nil

### ISSUE THREAD

**Issue by conao3** [conao3/leaf.el#426]
Handle :ensure nil.
This enables temporally disable auto :ensure t for the user who have configure `(setq leaf-defaults '(:ensure t))`

**Comment by arkhan** [comment]
Saludos.

Esto también funciona para :straight..?

**Comment by conao3** [comment]
Thanks comment. I'll add the related feature to `:el-get`, `:straight` keywords. Opened conao3/leaf-keywords.el/issues/108.
