### ISSUE TITLE
Question about behavior of `:leaf-defer t`

### ISSUE THREAD

**Issue by tpadioleau** [conao3/leaf.el#434]
## Description

Hello, I am testing `leaf.el` package with my `init.el` file currently using `use-package`. My problem is that `:leaf-defer` seems a bit different from `:defer`. In `use-package` if you set `:defer t` it forces deferring even if you don't use `:bind`, `:mode`, etc... It can be useful when you just need to change variables in a `:config` section. Is there a reason not to do that in `leaf.el` ?

## Issue leaf-block
```elisp
(leaf hoge
  :leaf-defer t
  :init (before-hoge-init)
  :config (hoge-init))
```

## Expected output from macroexpand-1 of the leaf-block
```elisp
(prog1 'hoge
  (leaf-handler-leaf-protect hoge
    (before-hoge-init)
    (eval-after-load 'hoge
      (hoge-init))))
```

In this example it would trigger "expensive" `(hoge-init)` function call only when you use an autoload function already defined in the hoge package.

Thank you

**Comment by conao3** [comment]
Thanks for using leaf.el :tada:

The `:defer` in the use-package seemed a bit confusing, so I split it into `:leaf-defer` and `:after`.
It may seem a little odd, but I consider it a reasonable choice.

And I hope that my two packages, [leaf-convert](https://github.com/conao3/leaf-convert.el) and [ppp](https://github.com/conao3/ppp.el) help you.

leaf-convert suggest you as follows.

```elisp
(leaf-convert
 (prog1 'hoge
   (before-hoge-init)
   (eval-after-load 'hoge
     (hoge-init))))
;;=> (leaf hoge
;;     :config
;;     (before-hoge-init)
;;     (eval-after-load 'hoge
;;       (hoge-init)))
```

It is should works well but there are more keyword-lize.
I recommend follows leaf block.

```elisp
(leaf hoge
  :init (before-hoge-init)
  :after t
  (hoge-init))

(ppp-macroexpand
 (leaf hoge
   :init (before-hoge-init)
   :after t
   (hoge-init)))
;;=> (prog1 'hoge
;;     (leaf-handler-leaf-protect hoge
;;       (eval-after-load 'hoge-init
;;         '(eval-after-load 'hoge
;;            '(progn
;;               (before-hoge-init))))))
```

How about this?

**Comment by tpadioleau** [comment]
> Thanks for using leaf.el tada
> 
> The `:defer` in the use-package seemed a bit confusing, so I split it into `:leaf-defer` and `:after`.
> It may seem a little odd, but I consider it a reasonable choice.

My way of seeing `:defer` in `use-package` was to put the content of `:config` inside `eval-after-load` unless `:defer` is `nil`.

I have just understood that keywords `:init` and `:config` in `leaf.el` are related to `require` and not `eval-after-load`.

> And I hope that my two packages, [leaf-convert](https://github.com/conao3/leaf-convert.el) and [ppp](https://github.com/conao3/ppp.el) help you.

Yes that's a reason why I wanted to try `leaf.el`.

> leaf-convert suggest you as follows.
> 
> ```emacs-lisp
> (leaf-convert
>  (prog1 'hoge
>    (before-hoge-init)
>    (eval-after-load 'hoge
>      (hoge-init))))
> ;;=> (leaf hoge
> ;;     :config
> ;;     (before-hoge-init)
> ;;     (eval-after-load 'hoge
> ;;       (hoge-init)))
> ```
> 
> It is should works well but there are more keyword-lize.
> I recommend follows leaf block.
> 
> ```emacs-lisp
> (leaf hoge
>   :init (before-hoge-init)
>   :after t
>   (hoge-init))
> 
> (ppp-macroexpand
>  (leaf hoge
>    :init (before-hoge-init)
>    :after t
>    (hoge-init)))
> ;;=> (prog1 'hoge
> ;;     (leaf-handler-leaf-protect hoge
> ;;       (eval-after-load 'hoge-init
> ;;         '(eval-after-load 'hoge
> ;;            '(progn
> ;;               (before-hoge-init))))))
> ```
> 
> How about this?

Would it work if `(hoge-init)` was replaced by `(setq var ...)` ?

**Comment by conao3** [comment]
Of course, yes!
But I mistook the snippet, it might confuse you. (I mistakenly dropped `:config` keyword)
```emacs-lisp
(ppp-macroexpand
 (leaf hoge
   :init (before-hoge-init)
   :after t
   :config
   (setq hoge t)))
;;=> (prog1 'hoge
;;     (leaf-handler-leaf-protect hoge
;;       (eval-after-load 'hoge
;;         '(progn
;;            (before-hoge-init)
;;            (setq hoge t)))))
```

Or, using `:custom` keyword is a better choice for this situation.
```emacs-lisp
(ppp-macroexpand
 (leaf hoge
   :init (before-hoge-init)
   :after t
   :custom (hoge . t)))
;;=> (prog1 'hoge
;;     (leaf-handler-leaf-protect hoge
;;       (eval-after-load 'hoge
;;         '(progn
;;            (custom-set-variables
;;             '(hoge t "Customized with leaf in hoge block"))
;;            (before-hoge-init)))))
```

**Comment by tpadioleau** [comment]
> Of course, yes!
> But I mistook the snippet, it might confuse you. (I mistakenly dropped `:config` keyword)
> 
> ```emacs-lisp
> (ppp-macroexpand
>  (leaf hoge
>    :init (before-hoge-init)
>    :after t
>    :config
>    (setq hoge t)))
> ;;=> (prog1 'hoge
> ;;     (leaf-handler-leaf-protect hoge
> ;;       (eval-after-load 'hoge
> ;;         '(progn
> ;;            (before-hoge-init)
> ;;            (setq hoge t)))))
> ```
> 
> Or, using `:custom` keyword is a better choice for this situation.
> 
> ```emacs-lisp
> (ppp-macroexpand
>  (leaf hoge
>    :init (before-hoge-init)
>    :after t
>    :custom (hoge . t)))
> ;;=> (prog1 'hoge
> ;;     (leaf-handler-leaf-protect hoge
> ;;       (eval-after-load 'hoge
> ;;         '(progn
> ;;            (custom-set-variables
> ;;             '(hoge t "Customized with leaf in hoge block"))
> ;;            (before-hoge-init)))))
> ```

It kind of work but still, `:init` statement is executed after `hoge` being loaded. Don't you think it is strange behavior ?

What about changing
```elisp
:leaf-defer (if (and leaf--body (eval (car leaf--value) (leaf-list-memq leaf-defer-keywords (leaf-plist-keys leaf--raw))))
                 `((eval-after-load ',leaf--name '(progn ,@leaf--body))) `(,@leaf--body))

```
to
```elisp
:leaf-defer (if (and leaf--body (or (eval (car leaf--value)) (leaf-list-memq leaf-defer-keywords (leaf-plist-keys leaf--raw))))
                 `((eval-after-load ',leaf--name '(progn ,@leaf--body))) `(,@leaf--body))
```
This way, by default, `:config` block is always executed after loading package, unless it is set to `nil` ?

**Comment by conao3** [comment]
Each keyword is well-designed, so you need to use the right keywords.
The `:init` is required to "run before `:require`", not "run before `:after`".
So, you might want to use `:preface`. This keyword is required to "run before the conditional branch keywords".

```elisp
(ppp-macroexpand
 (leaf hoge
   :preface (before-hoge-init)
   :after t
   :custom (hoge . t)))
;;=> (prog1 'hoge
;;     (before-hoge-init)
;;     (eval-after-load 'hoge
;;       '(progn
;;          (custom-set-variables
;;           '(hoge t "Customized with leaf in hoge block")))))
```

If I run `:init` before `:after` as you say, the following configuration will not work.
```elisp
(leaf hoge1
  :bind ("C-c c" . hoge1-compile))

(leaf hoge2
  :after hoge1
  :init (hoge1-integration)
  :config (hoge2-init))
```
When the `hoge1-integration` of `hoge2` is executed, we expect the hoge to be required, since `:after hoge1` is specified.
However, expanding `:init` before `:after` causes `hoge1-integration` to be executed unconditionally and causes an undefined error.
(if `hoge1-integration` is not set to autoload)

**Comment by tpadioleau** [comment]
> Each keyword is well-designed, so you need to use the right keywords.
> The `:init` is required to "run before `:require`", not "run before `:after`".

I agree, I may not explain well. I just wanted to ask for a different default behavior. If I take your example

> ```emacs-lisp
> (leaf hoge1
>   :bind ("C-c c" . hoge1-compile))
> 
> (leaf hoge2
>   :after hoge1
>   :init (hoge1-integration)
>   :config (hoge2-init))
> ```

Even having an implicit `:leaf-defer` default to `t`, it currently expands to
```elisp
(prog1 'hoge2
  (leaf-handler-leaf-protect hoge2
    (eval-after-load 'hoge1
      '(progn
         (hoge1-integration)
         (hoge2-init)))))
```
What about expanding it to
```elisp
(prog1 'hoge2
  (leaf-handler-leaf-protect hoge2
    (eval-after-load 'hoge1
      '(progn
         (hoge1-integration)
         (eval-after-load 'hoge2
           '(progn
              (hoge2-init)))))))
```
And keep first expansion when user sets `:leaf-defer` to `nil` ?

For now, when none of the `leaf-defer-keywords` is present, implicit or explicit `:leaf-defer t` does not put the `eval-after-load 'hoge2`. There is no intention to change ordering. Do you see what I mean ?

`:after t` clause does not seem enough in that case. I get this:
```elisp
(prog1 'hoge2
  (leaf-handler-leaf-protect hoge2
    (eval-after-load 'hoge1
      '(eval-after-load 'hoge2
         '(progn
            (hoge1-integration)
            (hoge2-init))))))
```

**Comment by conao3** [comment]
OK, I understand. I want to organize this story.

You want to below `leaf`
```elisp
(leaf hoge2
  :after hoge1
  :init (hoge1-integration)
  :config (hoge2-init))
```
expands to below sexp?
```elisp
(prog1 'hoge2
  (leaf-handler-leaf-protect hoge2
    (eval-after-load 'hoge1
      '(progn
         (hoge1-integration)
         (eval-after-load 'hoge2
           '(progn
              (hoge2-init)))))))
```

As you say, this issue is not a change ordering issue.
You get this behavior if you config `leaf-defer-keywords` as below.

```elisp
(leaf leaf
  :custom ((leaf-defer-keywords . '(:after
                                    :bind :bind*
                                    :mode :interpreter :magic :magic-fallback
                                    :hook :commands))))
;;=> leaf

(setq leaf-expand-minimally t)
;;=> t

(ppp-macroexpand
 (leaf hoge2
   :after hoge1
   :init (hoge1-integration)
   :config (hoge2-init)))
;;=> (prog1 'hoge2
;;     (eval-after-load 'hoge1
;;       '(progn
;;          (hoge1-integration)
;;          (eval-after-load 'hoge2
;;            '(progn
;;               (hoge2-init))))))
```

**Comment by tpadioleau** [comment]
> ```emacs-lisp
> (leaf leaf
>   :custom ((leaf-defer-keywords . '(:after
>                                     :bind :bind*
>                                     :mode :interpreter :magic :magic-fallback
>                                     :hook :commands))))
> ;;=> leaf
> 
> (setq leaf-expand-minimally t)
> ;;=> t
> 
> (ppp-macroexpand
>  (leaf hoge2
>    :after hoge1
>    :init (hoge1-integration)
>    :config (hoge2-init)))
> ;;=> (prog1 'hoge2
> ;;     (eval-after-load 'hoge1
> ;;       '(progn
> ;;          (hoge1-integration)
> ;;          (eval-after-load 'hoge2
> ;;            '(progn
> ;;               (hoge2-init))))))
> ```

This seems a good idea but specific to this situation. However how would you handle this simple leaf ?

```elisp
 (leaf hoge
   :init (hoge-init)
   :config (hoge-config))
```

That's why I proposed a behavior close to `use-package`:
unless `:leaf-defer` is set by user to `nil`, use `eval-after-load` if it is set by user to `t` or if a keyword in `leaf-defer-keywords` is found ?

**Comment by conao3** [comment]
> However how would you handle this simple leaf ?
 (leaf hoge
   :init (hoge-init)
   :config (hoge-config))

Nothing.

This behavior is just a difference between a `leaf` and a `use-package`. ((Same as the `use-package` in `(setq use-package-always-defer t)`)
```elisp
(ppp-macroexpand
 (leaf hoge
   :init (hoge-init)
   :config (hoge-config)))
;;=> (prog1 'hoge
;;     (hoge-init)
;;     (hoge-config))
```
If the user want to convert a `use-package` to a `leaf`, it is recommended to use `leaf-convert`.
```elisp
(ppp-sexp
 (leaf-convert
  (use-package hoge
    :init (hoge-init)
    :config (hoge-config))))
;;=> (leaf hoge
;;     :init
;;     (hoge-init)
;;     :require t
;;     :config
;;     (hoge-config))
```

> unless :leaf-defer is set by user to nil, use eval-after-load if it is set by user to t or if a keyword in leaf-defer-keywords is found ?

Sorry, I can't grasp what you mentioned.

**Comment by conao3** [comment]
Why can `require` be omitted? It's common for `hoge-config` to have an `autoload` set up and `hoge` is `require`d to be executed before `hoge-config` is executed.
