### ISSUE TITLE
Question about asterisks in (leaf <title>)

### ISSUE THREAD

**Issue by ppoloskov** [conao3/leaf.el#440]
## Description

In some configs I see 
`
(leaf *emacs-buildin
;;;
(leaf *default-keybind
;;;
))
`
 I wonder if there is any particular meaning of this asterisk and what the difference will it make with '(leaf emacs-buildin ... )' ?

**Comment by conao3** [comment]
Nothing. `*` is just a marker which tells me "this leaf is just a folder `leaf` not a package."
Actually, leaf expands leaf--name as prog1 1st argument symbol.
This symbol doesn't contribute anything. Again, just a marker. Please use counsel-imenu and see what happen.

This snippet using [ppp.el](https://github.com/conao3/ppp.el).
```emacs-lisp
(ppp-macroexpand
 (leaf *emacs-buildin
   :config
   (leaf dired
     :custom ((dired-dwim-target . t)))
   (leaf eldoc
     :custom ((eldoc-idle-delay . 0.3)))))
;;=> (prog1 '*emacs-buildin
;;     (leaf-handler-leaf-protect *emacs-buildin
;;       (leaf dired
;;         :custom ((dired-dwim-target . t)))
;;   
;;       (leaf eldoc
;;         :custom ((eldoc-idle-delay . 0.3)))))
```

**Comment by ppoloskov** [comment]
So, basically if I just drop the asterisk and name the folder just `(leaf emacs-buildin ... )` will it still work?

**Comment by conao3** [comment]
Yes, it is.
Note: `leaf` don't understand whether the first argument is a **package name** or just a **folder name**.
Therefore, it is important to note that no warnings will be displayed if you use a keyword that is expanded by omitting `leaf--name`.

Here is a folder called `emacs-buildin`, but you mistakenly used the `:hook` keyword for example.
Then the `leaf` will generate `add-hook` and related S-expressions as if a legitimate `leaf--name` were specified.

```emacs-lisp
(ppp-macroexpand
 (leaf emacs-buildin
   :hook (dired-mode-hook)              ; broken specification
   :config
   (leaf dired
     :custom ((dired-dwim-target . t)))))
;;=> (prog1 'emacs-buildin
;;     (leaf-handler-leaf-protect emacs-buildin
;;       (unless (fboundp 'emacs-buildin-mode)
;;         (autoload #'emacs-buildin-mode "emacs-buildin" nil t)) ; meaningless Sexp
;;       (declare-function emacs-buildin-mode "emacs-buildin")    ; meaningless Sexp
;;       (add-hook 'dired-mode-hook #'emacs-buildin-mode)         ; meaningless Sexp
;;       (eval-after-load 'emacs-buildin
;;         '(progn
;;            (leaf dired
;;              :custom ((dired-dwim-target . t)))))))
```

**Comment by ppoloskov** [comment]
Thank you for the detailed explanation. Maybe it should be reflected in documentation, because I was searching for the explanation all over the internet and even checked use-package docs...

**Comment by conao3** [comment]
Good, thanks for your point!
As I'm working on completely rewrite `leaf` documentation, I notify that when I complete that job.
