### ISSUE TITLE
leaf-enable-imenu-supportによるimenu表示がconfig引数に渡されたleaf断片をサポートしていない

### ISSUE THREAD

**Issue by ncaq** [conao3/leaf.el#443]
## Description

leafのimenu連携が`:config`に渡されたleaf断片を出力しません.

例えば

```elisp
(leaf scala-mode
  :ensure t
  :after t
  :init
  (defun lsp-format-before-save ()
    (add-hook 'before-save-hook 'lsp-format-buffer nil t))
  :hook (scala-mode-hook . lsp-format-before-save)
  :config (leaf lsp-metals :ensure t :require t))
```

のように書いてあるとlsp-metalsをimenuで出力しません.
`:config`の後に改行を入れると出力します.

`leaf-enable-imenu-support`の正規表現でサポートしていないようです.

仕様か悩みましたがとりあえずissueを建てます.

**Comment by conao3** [comment]
ありがとうございます。

正規表現を変えました。
誤検出が増えてるかもしれませんが、まぁそちらの方に振るということで。
ただ、CIがなぜか落ちてるので明日まで待ってみます。

**Comment by conao3** [comment]
MELPAのビルドが走ったので、アップデートしてもらうと今のHEADが降ってくると思います。
確認してもらえますか？

**Comment by ncaq** [comment]
確認いたしました.
対応ありがとうございます.
