### ISSUE TITLE
I can't load dashboard

### ISSUE THREAD

**Issue by AndersonTorres** [conao3/leaf.el#457]
## Description

Hello!

I am translating my current configuration, changing from use-package to leaf.

Everything is running OK for now, except [dashboard](https://github.com/emacs-dashboard/emacs-dashboard). It doesn't load as expected, it looks like if it was ignored.
On the other hand, the various `dashboard-`  variables and functions are still there.

The official page suggests this in order to configure dashboard:

```elisp
(use-package dashboard
  :ensure t
  :config
  (dashboard-setup-startup-hook))
```

Using leaf-convert, I obtained it:

```elisp
(leaf dashboard :ensure t :require t :config (dashboard-setup-startup-hook))
```
But the screen doesn't appear.

**Comment by conao3** [comment]
Thanks for your interested in my package!
I also use dashboard too, but there're no issues (My leaf is almost identical to yours. In fact, `dashboard-setup-startup-hook` is set to `autoload`, so require is not necessary in this case.)

However, when I tried to start the dashboard in a minimal environment, it did not see dashbord buffer.
I have a feeling this is a problem that will be solved by dashboard first.

```emacs-lisp
;;; init.el --- Sample clean init.el  -*- lexical-binding: t; -*-

;; ~/.debug.emacs.d/dashboard/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/dashboard/init.el'
(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(prog1 "leaf"
  (custom-set-variables
   '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                        ("melpa" . "https://melpa.org/packages/")
                        ("gnu"   . "https://elpa.gnu.org/packages/"))))
  (package-initialize)
  (unless (package-installed-p 'leaf)
    (package-refresh-contents)
    (package-install 'leaf)))



(load (locate-user-emacs-file "../essentials.el"))

(setq command-line-args '("emacs"))     ; remove condition hack

(dashboard-setup-startup-hook)

;; (defun dashboard-setup-startup-hook ()
;;   "Setup post initialization hooks.
;; If a command line argument is provided,
;; assume a filename and skip displaying Dashboard."
;;   (when (< (length command-line-args) 2 )
;;     (add-hook 'after-init-hook (lambda ()
;;                                  ;; Display useful lists of items
;;                                  (dashboard-insert-startupify-lists)))
;;     (add-hook 'emacs-startup-hook '(lambda ()
;;                                      (switch-to-buffer "*dashboard*")
;;                                      (goto-char (point-min))
;;                                      (redisplay)))))

;; Eval directory, but this doesn't work...
;; (add-hook 'after-init-hook (lambda ()
;;                                  ;; Display useful lists of items
;;                                  (dashboard-insert-startupify-lists)))
;; (add-hook 'emacs-startup-hook '(lambda ()
;;                                  (switch-to-buffer "*dashboard*")
;;                                  (goto-char (point-min))
;;                                  (redisplay)))
```

**Comment by AndersonTorres** [comment]
As I have seen in https://github.com/emacs-dashboard/emacs-dashboard/issues/237, you said it creates a \*dashboard\* buffer, but it doesn't come to top.

In my current setup, that buffer isn't even created at all. Maybe it is a bit more serious than I think.

(Well, I need to say my setup is a bit unorthodox: I use [Nixpkgs/NixOS](https://github.com/NixOS/nixpkgs) in order to call the ELPA packages, but it isn't to affect the ending result after all...)

**Comment by conao3** [comment]
hmm, I have below `leaf` for `dashboard` in init.el and works well.
```emacs-lisp
(leaf dashboard
  :doc "A startup screen extracted from Spacemacs"
  :req "emacs-25.3" "page-break-lines-0.11"
  :tag "dashboard" "tools" "screen" "startup" "emacs>=25.3"
  :url "https://github.com/emacs-dashboard/emacs-dashboard"
  :added "2020-03-26"
  :emacs>= 25.3
  :ensure t
  :defun (dashboard-setup-startup-hook)
  :config
  (dashboard-setup-startup-hook))
```
please try this?

**Comment by AndersonTorres** [comment]
Oh, this is worse than I think... 

Now I see a thing that explains all. A bit more background first:

A not so long time ago, I liked to test diverse configurations. I tried Spacemacs and Prelude before my own custom setup via `use-package`.

In order to switch between those various setups, I use [Chemacs](https://github.com/plexus/chemacs). It allows you to choose between various setups located in separate directories; those can be chosen via commandline, like this: `emacs --with-profile test-leaf`.

Further, you can set a default configuration in a specific file, `~/.emacs-profile`.

**But** if I am not wrong dashboard assumes commandline arguments as filenames and skip itself. Indeed, I have seen those lines:

```lisp
;; (defun dashboard-setup-startup-hook ()
;;   "Setup post initialization hooks.
;; If a command line argument is provided,
;; assume a filename and skip displaying Dashboard."
. . .
```

Indeed, when I set the leaf configuration as default via `~/.emacs-profile`, it loads dashboard without problems.

That way, it becomes impossible to use dashboard with chemacs.

P.S.: I have tried your configuration, and it worked the same way: if the profile is not default then dashboard is not loaded.

**Comment by conao3** [comment]
> Indeed, when I set the leaf configuration as default via ~/.emacs-profile, it loads dashboard without problems.
That way, it becomes impossible to use dashboard with chemacs.

? you can enable dashbord via leaf?

Anyway, leaf is just a macro,
```emacs-lisp
(leaf dashboard
  :ensure t
  :require t
  :config (dashboard-setup-startup-hook))
```

generates

```emacs-lisp
(prog1 'dashboard
  (condition-case err
      (progn
        (unless (package-installed-p 'dashboard)
          (unless (assoc 'dashboard package-archive-contents)
            (package-refresh-contents))
          (condition-case _err
              (package-install 'dashboard)
            (error
             (condition-case err
                 (progn
                   (package-refresh-contents)
                   (package-install 'dashboard))
               (error
                (display-warning 'leaf
                                 (format "In `dashboard' block, failed to :package of dashboard.  Error msg: %s"
                                         (error-message-string err))))))))
        (require 'dashboard)
        (dashboard-setup-startup-hook))
    (error
     (display-warning 'leaf
                      (format "Error in `dashboard' block.  Error msg: %s"
                              (error-message-string err))))))
```
That all for `leaf` side.  (you can use `macroexpand` to see this result)
Beyond this, I have a feeling it's a problem with dashboard or some other package you're using.

**Comment by AndersonTorres** [comment]
>  ? you can enable dashbord via leaf?

When I call emacs without parameters, using either your or my snippet, it loads dashboard as its "startup screen".

If I use any commandline args, it just skips dashboard completely, regardless the snippet used.

Maybe it can't be easily solved. After all, your minimal init needs commandline arguments: `emacs -q -l ~/.debug.emacs.d/dashboard/init.el`

**Comment by mtreca** [comment]
@AndersonTorres I don't think leaf is the culprit, but rather NixOS. I simply use use-package and are facing the same issue...

**Comment by AndersonTorres** [comment]
@mtreca I think the problem is in the method dashboard uses in order to decide it it will display itself or not.

If a command line argument is used, dashboard thinks it is a file name. Because of it, it is impossible to use chemacs, at least in a regular way.

**Comment by conao3** [comment]
It seems to issue on dashboard or Nix. please reopen this if you have another point or any questions.
