### ISSUE TITLE
use `load-file-name' in `leaf-handler-leaf-protect'

### ISSUE THREAD

**Issue by Z572** [conao3/leaf.el#461]
``` lisp
(defmacro leaf-handler-leaf-protect (name &rest body)
  "Meta handler for :leaf-protect in NAME for BODY `leaf' block."
  (declare (indent 1))
  `(condition-case err
       (progn ,@body)
     (error
      (display-warning 'leaf (format ,(format "Error in `%s' file `%s' block.  Error msg: %%s" load-file-name name)
                                     (error-message-string err))))))
```
The user can see which file the error occurred in.

**Comment by conao3** [comment]
Good suggestion! Could you send PR?

**Comment by Z572** [comment]
Yes, I can. Do I need to sign FSF?

**Comment by conao3** [comment]
Usually, less than a week. There's no need to rush. I'm happy to welcome our new contributor!

**Comment by conao3** [comment]
Any progress?

**Comment by Z572** [comment]
I signed PDF and sent it, but I haven't received a digital copy. Don't know if I can send PR.

**Comment by Z572** [comment]
I signed PDF and sent it, but I haven't received a digital copy. Don't know if I can send PR.

**Comment by conao3** [comment]
I don't know too... Please ask the FSF clerk what you should do.

**Comment by Z572** [comment]
Now I received the digital copy.
