### ISSUE TITLE
leaf + (emacs-lisp) flycheck 

### ISSUE THREAD

**Issue by reuleaux** [conao3/leaf.el#464]
I am just starting out with _leaf,_ so bear with me, please,
and I am rewriting my _use-package_ config to use _leaf_.

All this is _emacs-lisp_ code, of course, and I had - since a long time -
_flycheck_ turned on to help me in this regard, like so

```elisp
(add-hook 'emacs-lisp-mode-hook (lambda ()
                                  (progn

				    (setq flycheck-checker #'emacs-lisp)				    
				    (flycheck-mode)
			    
                                    ) ;; progn
				  ) ;; lambda
	  ) ;; add hook
``` 
Now, take my _leaf_ config for _ivy_ just as an example - created with the help of _leaf-convert_ -
(the problem that I am about to describe holds for any other _leaf_ config as well)
```elisp
(leaf ivy
  :bind (

         (global-map
          ("C-c C-r" . ivy-resume))


         ;; exchange the default bindings for C-j and C-m (return)
         ;; i.e. tab-tab waits in minibuffer

         (ivy-minibuffer-map

          ;; ret (default C-j)
          ("<return>" . ivy-alt-done)

          ;; (default C-m , i.e. ret )
          ("C-j" . ivy-done)

          ;; tab-tab returns as done,   (default ivy-partial-or-done )
          ("<tab>" . #'ivy-partial)

          ;; corresponds to M-y for counsel-yank-pop
          ("M-y" . #'ivy-next-line))
         )


  :setq (
         (ivy-use-virtual-buffers . t)
         (ivy-display-style 'fancy)
         )

  :config
  (ivy-mode 1)
  )
```
This seems to work (emacs starts fine with this) - however my _emacs-lisp flychecker_ complains:
```
In toplevel form:
_ivy-counsel-amx-swiper.el:5:1:Error: Wrong type argument: listp, ivy-alt-done
```
and I can make it happy by function-quoting _ivy-alt-done_ and _ivy-done_ in the _:bind_ section
```elisp
...
("<return>" . #'ivy-alt-done)
("C-j" . #'ivy-done)
```
instead of just 
```elisp
...
("<return>" . ivy-alt-done)
("C-j" . ivy-done)
```
however, now that _flycheck_ is happy, my emacs won't start up properly any more
```
Warning (initialization): An error occurred while loading ‘/home/rx/.emacs.d/init.el’:

Wrong type argument: listp, <return>

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
It would certainly be nice to have both working: _leaf_ and _emacs-lisp flycheck_.
Thanks,
  Andreas

**Comment by conao3** [comment]
Thanks, report. But I think, I think your Emacs doesn't load `leaf` in compiling-time?
I try this init.el and byte-compille made missing variable and missing function warning.

```
;;; init.el --- Sample clean init.el  -*- lexical-binding: t; -*-

;; ~/.debug.emacs.d/leaf-byte-compile-ivy/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/leaf-byte-compile-ivy/init.el'
(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(eval-when-compile
  (setq user-emacs-directory
        (expand-file-name (file-name-directory default-directory))))

(eval-and-compile
  (prog1 "leaf"
    (custom-set-variables
     '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                          ("melpa" . "https://melpa.org/packages/")
                          ("gnu"   . "https://elpa.gnu.org/packages/"))))
    (package-initialize)
    (unless (package-installed-p 'leaf)
      (package-refresh-contents)
      (package-install 'leaf))))



(load (locate-user-emacs-file "../essentials.el"))

(leaf ivy
  :bind ((global-map
          ("C-c C-r" . ivy-resume))
         (ivy-minibuffer-map
          ("<return>" . ivy-alt-done)
          ("C-j" . ivy-done)
          ("<tab>" . ivy-partial)
          ("M-y" . ivy-next-line)))
  :setq ((ivy-use-virtual-buffers . t)
         (ivy-display-style 'fancy))
  :config
  (ivy-mode 1))
```
```
$ emacs --version
GNU Emacs 27.1
Copyright (C) 2020 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

$ emacs --batch -f batch-byte-compile init.el
In toplevel form:
init.el:37:11:Warning: assignment to free variable ‘ivy-use-virtual-buffers’
init.el:38:11:Warning: assignment to free variable ‘ivy-display-style’

In end of data:
init.el:41:1:Warning: the function ‘ivy-mode’ is not known to be defined.
```
---
And please fix leaf form like below
```
(leaf ivy
  :bind ((global-map
          ("C-c C-r" . ivy-resume))
         (ivy-minibuffer-map
          ("<return>" . ivy-alt-done)
          ("C-j" . ivy-done)
          ("<tab>" . ivy-partial)
          ("M-y" . ivy-next-line)))
  :custom ((ivy-use-virtual-buffers . t)
           (ivy-display-style 'fancy))
  :global-minor-mode t)
```

```
$ emacs --batch -f batch-byte-compile init.el
```
byte-compile happy now.

**Comment by reuleaux** [comment]
Hi, thanks for your feedback, and yes, indeed,
I haven't byte-compiled my code - so far -, but I will give it a try.

I have been using _straight.el_ (instead of the emacs built in
package-initialize / package-install ), like so

```elisp
 (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))


  (straight-use-package 'leaf)
  (straight-use-package 'leaf-keywords)
  (straight-use-package 'leaf-convert)


  (straight-use-package 'use-package)
  (straight-use-package 'flycheck)
  ...
```

(more details to be found on the _straight.el_ website), and all
this on top of my emacs installed from debian bullseye/testing,
i.e. debian packages `emacs`, `auto-complete-el`, `elpa-dash`, `elpa-s`,
`hasktags`, `elpa-magit`, `elpa-ivy`, ...

This may already be some source of confusion: installing _some_ _emacs_ packages
from _Debian_, and _some_ via _straight.el_ (which in turn uses _elpa_,
_melpa_, _gnu_, ...), but so far this has worked well for me: having
some packages installed from Debian made my list of _straight.el_
installed packages shorter.

Now adding _leaf_ to that mix (in my naive way) seems to break some
bits. - I did see akhan's initfile
`https://github.com/arkhan/emacs.d` (via
`https://github.com/conao3/leaf.el/issues/306`),
and apparently he uses straight's develpment branch:
```
(setq straight-repository-branch "develop"
      straight-base-dir conf:cache-dir
      straight-check-for-modifications '(check-on-save-find-when-checking))
      ;;straight-vc-git-default-clone-depth 100)
...
```
(I am not quite sure, if this is needed really ?), and likewise later:
```
(require 'straight-x)
```
(haven't seen this before either), but this config seems to work for
him.

OK, I will thus continue to experiment with my config, and start from a
clean (minimal) init.el, and byte-compile my code, as you suggest,
and hopefully will be able to do so with _straight.el_
OK, thanks so far.
  -Andreas

**Comment by reuleaux** [comment]
OK, I am progressing slowly.

With the advice you have given me, I have a rather minimal init.el
(in terms of straight.el even, and wich uses my debian emacs packages
as well). - And I am byte-compiling my init file now: so I can
see many errors early on.

Now, next problem (in the context of an otherwise working init.el file
-- showing just the relevant part here):


I cannot use lambdas in :bind like so

```
(leaf flycheck

  

   :bind
    (
     
     ("C-<f5>" . flycheck-next-error)

     ("C-<f6>" . flycheck-previous-error)
     
     
     
     ( "C-S-<f5>" . (lambda ()
		      (interactive)
		      (progn
                        (flycheck-compile flycheck-checker)
                        )
		      ))

     ) 


)


```

In use-package this was not a problem, and it would be nice
to bind lambdas to key sequences as well.


If I comment out the offending binding, everythings works
fine:


```
(leaf flycheck

  

   :bind
    (
     
     ("C-<f5>" . flycheck-next-error)

     ("C-<f6>" . flycheck-previous-error)
     
     
     ;; ( "C-S-<f5>" . (lambda ()
     ;; 		      (interactive)
     ;; 		      (progn
     ;;                    (flycheck-compile flycheck-checker)
     ;;                    )
     ;; 		      ))
     

)
```

Thanks in advance.
  Andreas



PS: And I really don't know why my (gh flavoured) markup didn't show up last time,
(I can only hope it works this time). I am using a normal mail client
(Gnus), not the github webinterface.

**Comment by conao3** [comment]
It seems `lambda` in `:bind` issue. closing this for a duplicate.
Please reopen you have another point.
