### ISSUE TITLE
Optional leaf-key-bindlist

### ISSUE THREAD

**Issue by xFA25E** [conao3/leaf.el#488]
## Description

Hi, it would be nice to have the feature of leaf-key-bindlist optional.  Leaf is
very good at byte-compiled configs, since it does not need itself at runtime
after byte-compilation.  The only minor inconvenience is that i does require a
(defvar leaf-key-bindlist nil) at the beginning of a config file to work.  I
wanted to disable this feature, since I don't use it.  I was thinking about a
variable like leaf-expand-minimally.  Should I send a PR?  Thanks!

**Comment by conao3** [comment]
Good sugestion! You want send PR? welcome!

**Comment by conao3** [comment]
If you don't have require `leaf` at runtime, will you get an undefined error in `leaf-key-bindlist`?

**Comment by xFA25E** [comment]
Well, during compilation, emacs expands all the macros.  Leaf `:bind` is expanded
with a `(push value leaf-key-bindlist)` form.  So, yeah, when you load init.el,
Emacs loads init.elc instead.  And since it can't find the `leaf-key-bindlist`
variable it signals and undefined error.

**Comment by xFA25E** [comment]
I'm having trouble running docker, but all tests passed.  Can I send you a patch
for leaf.el and leaf-tests.el.

**Comment by conao3** [comment]
yes. As you send PR, GitHub Actions will run test on each Emacs versions.

**Comment by conao3** [comment]
Sorry, `make test` is broken now. if `make check` is green, your patch will be fine.

**Comment by xFA25E** [comment]
Ok, I've sent an assignment email. Waiting for a response. Then I wil sent a PR

**Comment by conao3** [comment]
Any updates?

**Comment by xFA25E** [comment]
Yeah, I'm almost done. Waiting for a final confirmation. Already, signed it and sent to gnu.

**Comment by xFA25E** [comment]
Hi, I've completed my assignment.

**Comment by conao3** [comment]
Good news!
