### ISSUE TITLE
Need (require 'leaf') in the init.el file? 

### ISSUE THREAD

**Issue by uwabami** [conao3/leaf.el#497]
From a slack conversation with @conao3 

`cat init.el`: 
```elisp
(package-initialize)
(unless (package-installed-p 'leaf)
  (package-refresh-contents)
  (package-install 'leaf t))
(leaf leaf-keywords :ensure t)
(leaf-keywords-init)
```
After byte-compiled, run emacs with the int.elc  cause this error:
   byte-code: Symbol’s function definition is void: leaf-this-file

@conao3 said: 
`leaf-this-file` should be macro.

Thanks.

**Comment by conao3** [comment]
Thanks! I try to solve this issue via #498. Please try it!

**Comment by uwabami** [comment]
Hmm. 

Next error:
```
Symbol's value as variable is void: leaf--load-file-name
````

Thanks.

**Comment by conao3** [comment]
well, then we need `(bound-and-true-p leaf--load-file-name)`

**Comment by conao3** [comment]
Merged. Please try it!

**Comment by uwabami** [comment]
It seems fine. Thanks!
