### ISSUE TITLE
add hook from separate package in current

### ISSUE THREAD

**Issue by jgarte** [conao3/leaf.el#516]
Hi,

How can I consolidate this?

```
(leaf eglot)
(add-hook 'eglot-managed-mode-hook #'eldoc-mode)
```

Any help is much appreciated.

**Comment by conao3** [comment]
You could choose one of these. I like the former one.
```
(leaf eglot
  :config
  (leaf eglot-mode
    :hook eglot-managed-mode-hook))

(leaf eglot
  :hook (eglot-managed-mode-hook . eglot-mode))
```

**Comment by conao3** [comment]
Oops, just this configuration is sufficient
```
(leaf eglot
  :hook eglot-managed-mode-hook)
```

**Comment by jgarte** [comment]
> You could choose one of these. I like the first one.
> 
> ```
> (leaf eglot
>   :config
>   (leaf eldoc-mode
>     :hook eglot-managed-mode-hook))
> 
> (leaf eglot
>   :hook (eglot-managed-mode-hook . eldoc-mode))
> 
> (leaf eglot
>   (leaf eglot-managed-mode
>     :mode-hook
>     (eldoc-mode)))
> ```

Thanks! I chose the first one :)

**Comment by jgarte** [comment]
I'd like to add this within my eglot config:

```
(add-hook 'rust-mode-hook 'eglot-ensure)

```

This is my current config:

```
(leaf eglot
  :config
  (leaf eldoc-mode
    :hook eglot-managed-mode-hook))
```

**Comment by conao3** [comment]
There are two ways to look at this.
The idea is to run `(eglot-ensure)` as a `rust-mode` setting. The other is to run `eglot` in `rust-mode`.
Both can be expressed in leaf. The important thing is how the you see it.

In the former case, use leaf as `(leaf rust-mode)`.
```elisp
(leaf rust-mode
  :hook (rust-mode-hook . eglot-ensure))
```
Or you can use `:mode-hook`.
```elisp
(leaf rust-mode
  :mode-hook
  (eglot-ensure))
```
In the latter case, configure leaf as `(leaf eglot)`.
```elisp
(leaf eglot
  :hook (rust-mode-hook . elgot-ensure))
```

And, you can explicitly configure a leaf to be evaluated after `rust-mode` has been loaded
```elisp
(leaf eglot
  :config
  (leaf *eglot--rust-mode
    :after rust-mode
    :hook (rust-mode-hook . eglot-ensure)))
```

You can choose one of these.
