### ISSUE TITLE
:custom (some . (myfunc))  Attempt modify list

### ISSUE THREAD

**Issue by hans-d** [conao3/leaf.el#520]
## Description

Having issues setting a custom variable using an expression.

## Issue leaf-block
```elisp
(leaf mytest
  :preface
  (defun myfunc() (concat "x" "y")
  :custom 
  (var1 . "xxx")
  (var2 . (myfunc))
)
```

**Comment by conao3** [comment]
Please tell me more concrete example?
To tell the truth, you attempt to modify list, the `leaf` error message is correct.

`leaf`'s `:custom` want to cons-cell, so your input is interpreted like below.
```elisp
(leaf mytest
  :custom 
  (var1 . "xxx")
  (var2 . (myfunc))
```
equals with...
```elisp
(leaf mytest
  :custom
  (var1 . "xxx")
  (var2 myfunc))
```
also equals with...
```elisp
(leaf mytest
  :custom
  (var1 . "xxx")
  (var2 myfunc . nil))
```
so `leaf` set `var1` as `"xxx"` and set `var2 myfunc` as `nil`. As you can see, latter one cannot execute.


Maybe you want
```elisp
(leaf mytest
  :preface
  (defun myfunc() (concat "x" "y"))
  :custom
  (var1 . "xxx")
  (var2 . #'myfunc))
```
or
```elisp
(leaf mytest
  :preface
  (defun myfunc() (concat "x" "y"))
  :custom
  (var1 . "xxx")
  (var2 . (lambda () (interactive) myfunc))
```
Is this any help to you?

**Comment by hans-d** [comment]
found that this is working / what I needed
```
(leaf mytest
  :preface
  (defun myfunc() (concat "x" "y"))
  :custom
  (var1 . "xxx")
  `(var2 \, (myfunc))
```
(these bits of elisp are still a bit black magic for me)

**Comment by conao3** [comment]
Oh, you want to set `var2` as return value of `(myfunc)`? I finally get it.
Once it worked, it is fine but I recommend this Sexp.
```elisp
(leaf mytest
  :preface
  (defun myfunc() (concat "x" "y"))
  :custom
  (var1 . "xxx")
  `(var2 . ,(myfunc)))
```

This technique is also used sample leaf [in readme](https://github.com/conao3/leaf.el#pre-setq-setq-setq-default-keywords) (but this is sample for `:setq`. This technique can be used any keyword as you can see).
```elisp
     ;; use backquote and comma to set result of sexp
     (leaf alloc
       :setq `((gc-cons-threshold . ,(* 512 1024 1024))
               (garbage-collection-messages . t))
       :require t)

     ;; will be...

     (prog1 'alloc
       (require 'alloc)
       (setq gc-cons-threshold 536870912)
       (setq garbage-collection-messages t))
```

**Comment by hans-d** [comment]
Thanks. Perhaps adding a sample of that to the `:custom` section as well?

**Comment by conao3** [comment]
Are you try?

**Comment by tangxinfa** [comment]
I try to configure dired-sidebar:

    (leaf dired-sidebar
      :custom
      (dired-sidebar-theme . (if window-system 'nerd 'ascii)))

And it accidentally set `window-system` to `nil`, take me too many time to
diagnose the problem. If i use `custom-set-variables`, it's difficult to make
this mistake because there is a `'` mark at the beginning:

    (custom-set-variables
        '(dired-sidebar-theme . `,(if window-system 'nerd 'ascii)))

**Comment by pedz** [comment]
I too had this issue and found this thread.  I think an example would help.  The lambda example, for me, just adds to the confusion although that might be just me.

Also... please consider opening the Discussions because I figured my issue was pilot error but had no real viable place to ask such a specific question.
