### ISSUE TITLE
Force fetch and installation of packages already in emacs core

### ISSUE THREAD

**Issue by dpassen** [conao3/leaf.el#522]
## Description

Is there a way using leaf.el to force package.el to fetch a more recent version of a package that is already included within emacs? For example, project.el or org mode.

## Issue leaf-block
```elisp
(leaf project
  :ensure t)
```

**Comment by conao3** [comment]
`leaf` is just expand `package.el` Sexp, so we need to know how to make package.el update its built-in packages.
Can you tell me how to do that? Currently, in a nutshell, the installation is unconditionally skipped if `project` is installed.
```elisp
(leaf project :ensure t)
```
into this
```elisp
(unless (package-installed-p 'project)
  (package-install 'project))
```

**Comment by dpassen** [comment]
I see. Thank you
