### ISSUE TITLE
Support package-vc in `:package` keyword

### ISSUE THREAD

**Issue by AkibAzmain** [conao3/leaf.el#532]
There is a new thing called `package-vc` in the Emacs master branch.  It's an alternative of Quelpa (sort of).  It would be nice to support it in `:ensure` and `:package` keyword.

**Comment by conao3** [comment]
Hi @AkibAzmain, I add `:vc` keyword 🎉  Could you try it?

**Comment by conao3** [comment]
Close for merging this feature
