### ISSUE TITLE
Use of "expand" in documentation is unclear

### ISSUE THREAD

**Issue by dabrahams** [conao3/leaf.el#535]
## Description

I understand that leaf is implemented by macros, but that's below the level of abstraction of this package for most users.  When I see docs like:

> - `leaf-expand-{{keyword}}`: If nil, not to expand that keyword.
> - `leaf-expand-minimally`: If nil, disable keywords that are not needed for debugging.

I don't know what it means to "not expand" a keyword.  The 2nd bullet leads me to believe a keyword that is not expanded is probably "disabled," which probably means it's ignored.  If my conclusions are correct, I'd change the first description to, “if nil, ignore any uses of that keyword” and ultimately I would rename all of these options to  `leaf-ignore-{{keyword}}` (when you figure out the migration story).

**Comment by conao3** [comment]
`leaf-expand-minimally` equals to `use-package-minimally`.

`use-package-minimally` is defined bellow.
https://github.com/jwiegley/use-package/blob/77945e002f11440eae72d8730d3de218163d551e/use-package-core.el#L284-L297
```
(defcustom use-package-expand-minimally nil
  "If non-nil, make the expanded code as minimal as possible.
This disables:
  - Printing to the *Messages* buffer of slowly-evaluating forms
  - Capturing of load errors (normally redisplayed as warnings)
  - Conditional loading of packages (load failures become errors)
The main advantage to this variable is that, if you know your
configuration works, it will make the byte-compiled file as
minimal as possible.  It can also help with reading macro-expanded
definitions, to understand the main intent of what's happening."
  :type 'boolean
  :group 'use-package)
```

Also use-package, use "expand" term, I don't mind the current description, but if you can suggest a better idea, I will consider it.

**Comment by dabrahams** [comment]
Thanks, but If I have to read `use-package` documentation to understand leaf, I'm definitely going back to use-package.  Part of the reason I'm here is that use-package isn't always easy to understand.  When I say docs are hard to understand, it means I don't know what an accurate description would be, and can't possibly make a better suggestion.

**Comment by dabrahams** [comment]
I think I'd better close this.  It doesn't seem like leaf is going to be any easier for me to understand than use-package is.  Thanks anyhow.
